package persistence.entities;
// Generated 29 mars 2021 à 17:42:30 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Compte generated by hbm2java
 */
@Entity
@Table(name = "COMPTE", schema = "TPBANQUE")
public class Compte implements java.io.Serializable {

	private BigDecimal numcompte;
	private BigDecimal solde;
	private String proprietaire;

	public Compte() {
	}

	public Compte(BigDecimal numcompte) {
		this.numcompte = numcompte;
	}

	public Compte(BigDecimal numcompte, BigDecimal solde, String proprietaire) {
		this.numcompte = numcompte;
		this.solde = solde;
		this.proprietaire = proprietaire;
	}

	@Id

	@Column(name = "NUMCOMPTE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getNumcompte() {
		return this.numcompte;
	}

	public void setNumcompte(BigDecimal numcompte) {
		this.numcompte = numcompte;
	}

	@Column(name = "SOLDE", precision = 22, scale = 0)
	public BigDecimal getSolde() {
		return this.solde;
	}

	public void setSolde(BigDecimal solde) {
		this.solde = solde;
	}

	@Column(name = "PROPRIETAIRE", length = 20)
	public String getProprietaire() {
		return this.proprietaire;
	}

	public void setProprietaire(String proprietaire) {
		this.proprietaire = proprietaire;
	}

}
